# Data Combination

## Example

In [ ]:
# Imports
import pandas as pd

# Define data
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [24, 30, 22, 35],
    "score": [88, 75, 90, 60],
    "group": ["A", "B", "A", "B"]
})

# Show data
df.head()

      name  age  score group
0    Alice   24     88     A
1      Bob   30     75     B
2  Charlie   22     90     A
3    David   35     60     B

## `merge`

Applies SQL-style joins.

In [4]:
# Define data
df2 = pd.DataFrame({
    'group': ['A', 'B'],
    'tutor': ['Dr Smith', 'Dr Jones']
})

# Merge
df_merged = pd.merge(df, df2, on = 'group', how = 'left')

# Show data
df_merged.head()

      name  age  score group     tutor
0    Alice   24     88     A  Dr Smith
1      Bob   30     75     B  Dr Jones
2  Charlie   22     90     A  Dr Smith
3    David   35     60     B  Dr Jones

## `concat`

Stacks DataFrames vertically or horizontally.

In [6]:
# Define data
df_top = df.iloc[:2]
df_bottom = df.iloc[2:]

print(df_top)
print()
print(df_bottom)

    name  age  score group
0  Alice   24     88     A
1    Bob   30     75     B

      name  age  score group
2  Charlie   22     90     A
3    David   35     60     B

### Vertical Stack

In [7]:
# Stack data
pd.concat([df_top, df_bottom], axis = 0)

      name  age  score group
0    Alice   24     88     A
1      Bob   30     75     B
2  Charlie   22     90     A
3    David   35     60     B

### Horizontal Stack

In [15]:
# Stack data
pd.concat([df_top.reset_index(drop = True), df_bottom.reset_index(drop = True)], axis = 1)

    name  age  score group     name  age  score group
0  Alice   24     88     A  Charlie   22     90     A
1    Bob   30     75     B    David   35     60     B