# Data Mapping

## Example

In [ ]:
# Imports
import pandas as pd

# Define data
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [24, 30, 22, 35],
    "score": [88, 75, 90, 60],
    "group": ["A", "B", "A", "B"]
})

# Show data
df.head()

      name  age  score group
0    Alice   24     88     A
1      Bob   30     75     B
2  Charlie   22     90     A
3    David   35     60     B

## `map`

In [2]:
# Define mapping
group_map = {'A': 'High', 'B': 'Low'}

# Apply mapping as new column
df['group_level'] = df['group'].map(group_map)

# Show data
df.head()

      name  age  score group group_level
0    Alice   24     88     A        High
1      Bob   30     75     B         Low
2  Charlie   22     90     A        High
3    David   35     60     B         Low