# Data Aggregation

## Example

In [ ]:
# Imports
import pandas as pd

# Define data
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [24, 30, 22, 35],
    "score": [88, 75, 90, 60],
    "group": ["A", "B", "A", "B"]
})

# Show data
df.head()

      name  age  score group
0    Alice   24     88     A
1      Bob   30     75     B
2  Charlie   22     90     A
3    David   35     60     B

## `groupby`

Groups data by one or more columns.

In [13]:
# Group data
df_grouped = df.groupby(by = 'group')[['age', 'score']]
# Perform some aggregation
df_grouped.mean()

        age  score
group
A      23.0   89.0
B      32.5   67.5

## `agg`

Apply multiple aggregations after `groupby()`

In [14]:
# Apply aggregation
df.groupby('group').agg({
    'score': ['mean', 'max', 'min'],
    'age': 'median'
})

      score            age
       mean max min median
group
A      89.0  90  88   23.0
B      67.5  75  60   32.5